-- Migration: Add PAINT_CONSUMED log type
-- When paint leaves the warehouse (STOCK_OUT) and residual is returned to
-- sideroom (SIDEROOM_IN), the difference is paint consumed during painting.
-- This new type is auto-generated by the server on every SIDEROOM_IN to
-- explicitly track that consumed amount.
--
-- Example: 180 kg STOCK_OUT, 5 kg SIDEROOM_IN → auto 175 kg PAINT_CONSUMED

ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'PAINT_CONSUMED';
